/**
 * HeroiconRegistry
 *
 * Maps Lucide icon names to their @heroicons/react equivalents (outline + solid).
 * Used by WantTypeVisuals.resolveIconForFamily when icon_font is 'heroicons-*'.
 *
 * Tree-shaking note: only icons listed here are included in the bundle.
 * Add new entries to extend coverage for YAML labels['type-icon'] values.
 */
import React from 'react';

// ── Outline ───────────────────────────────────────────────────────────────────
import {
  AdjustmentsHorizontalIcon as O_Adjustments,
  ArchiveBoxIcon            as O_Archive,
  ArrowDownTrayIcon         as O_Download,
  ArrowPathIcon             as O_Refresh,
  ArrowUpTrayIcon           as O_Upload,
  Bars3Icon                 as O_Menu,
  BeakerIcon                as O_Beaker,
  BellIcon                  as O_Bell,
  BookmarkIcon              as O_Bookmark,
  BoltIcon                  as O_Bolt,
  CalendarIcon              as O_Calendar,
  CameraIcon                as O_Camera,
  ChartBarIcon              as O_ChartBar,
  ChatBubbleLeftIcon        as O_MessageSquare,
  ChatBubbleOvalLeftIcon    as O_MessageCircle,
  CheckCircleIcon           as O_CheckCircle,
  CircleStackIcon           as O_Database,
  ClockIcon                 as O_Clock,
  CloudIcon                 as O_Cloud,
  CodeBracketIcon           as O_Code,
  Cog6ToothIcon             as O_Settings,
  CommandLineIcon           as O_Terminal,
  ComputerDesktopIcon       as O_Monitor,
  CubeIcon                  as O_Box,
  DevicePhoneMobileIcon     as O_Smartphone,
  DocumentCheckIcon         as O_Clipboard,
  EnvelopeIcon              as O_Mail,
  ExclamationCircleIcon     as O_AlertCircle,
  ExclamationTriangleIcon   as O_AlertTriangle,
  EyeIcon                   as O_Eye,
  FireIcon                  as O_Flame,
  FolderIcon                as O_Folder,
  FolderOpenIcon            as O_FolderOpen,
  FunnelIcon                as O_Filter,
  GlobeAltIcon              as O_Globe,
  HandThumbDownIcon         as O_ThumbsDown,
  HandThumbUpIcon           as O_ThumbsUp,
  HeartIcon                 as O_Heart,
  HomeIcon                  as O_Home,
  InformationCircleIcon     as O_Info,
  LightBulbIcon             as O_Lightbulb,
  LinkIcon                  as O_Link,
  ListBulletIcon            as O_List,
  LockClosedIcon            as O_Lock,
  LockOpenIcon              as O_Unlock,
  MagnifyingGlassIcon       as O_Search,
  MapIcon                   as O_Map,
  MapPinIcon                as O_MapPin,
  MoonIcon                  as O_Moon,
  MusicalNoteIcon           as O_Music,
  PaperAirplaneIcon         as O_Plane,
  PauseIcon                 as O_Pause,
  PauseCircleIcon           as O_PauseCircle,
  PencilIcon                as O_Edit2,
  PencilSquareIcon          as O_Edit,
  PhoneIcon                 as O_Phone,
  PhotoIcon                 as O_Image,
  PlayIcon                  as O_Play,
  PlayCircleIcon            as O_PlayCircle,
  PlusIcon                  as O_Plus,
  PlusCircleIcon            as O_PlusCircle,
  PowerIcon                 as O_Power,
  QuestionMarkCircleIcon    as O_HelpCircle,
  RectangleGroupIcon        as O_Layout,
  RectangleStackIcon        as O_Layers,
  CalculatorIcon            as O_Calculator,
  ServerIcon                as O_Server,
  ServerStackIcon           as O_ServerStack,
  ShareIcon                 as O_Share2,
  ShieldCheckIcon           as O_Shield,
  ShieldExclamationIcon     as O_ShieldAlert,
  ShoppingBagIcon           as O_ShoppingBag,
  ShoppingCartIcon          as O_ShoppingCart,
  SpeakerWaveIcon           as O_Volume2,
  SpeakerXMarkIcon          as O_VolumeX,
  StarIcon                  as O_Star,
  StopIcon                  as O_Stop,
  StopCircleIcon            as O_StopCircle,
  SunIcon                   as O_Sun,
  TagIcon                   as O_Tag,
  TrashIcon                 as O_Trash,
  TrophyIcon                as O_Trophy,
  UserIcon                  as O_User,
  UsersIcon                 as O_Users,
  VideoCameraIcon           as O_Video,
  WifiIcon                  as O_Wifi,
  WrenchIcon                as O_Wrench,
  XCircleIcon               as O_XCircle,
  XMarkIcon                 as O_X,
} from '@heroicons/react/24/outline';

// ── Solid ─────────────────────────────────────────────────────────────────────
import {
  AdjustmentsHorizontalIcon as S_Adjustments,
  ArchiveBoxIcon            as S_Archive,
  ArrowDownTrayIcon         as S_Download,
  ArrowPathIcon             as S_Refresh,
  ArrowUpTrayIcon           as S_Upload,
  Bars3Icon                 as S_Menu,
  BeakerIcon                as S_Beaker,
  BellIcon                  as S_Bell,
  BookmarkIcon              as S_Bookmark,
  BoltIcon                  as S_Bolt,
  CalendarIcon              as S_Calendar,
  CameraIcon                as S_Camera,
  ChartBarIcon              as S_ChartBar,
  ChatBubbleLeftIcon        as S_MessageSquare,
  ChatBubbleOvalLeftIcon    as S_MessageCircle,
  CheckCircleIcon           as S_CheckCircle,
  CircleStackIcon           as S_Database,
  ClockIcon                 as S_Clock,
  CloudIcon                 as S_Cloud,
  CodeBracketIcon           as S_Code,
  Cog6ToothIcon             as S_Settings,
  CommandLineIcon           as S_Terminal,
  ComputerDesktopIcon       as S_Monitor,
  CubeIcon                  as S_Box,
  DevicePhoneMobileIcon     as S_Smartphone,
  DocumentCheckIcon         as S_Clipboard,
  EnvelopeIcon              as S_Mail,
  ExclamationCircleIcon     as S_AlertCircle,
  ExclamationTriangleIcon   as S_AlertTriangle,
  EyeIcon                   as S_Eye,
  FireIcon                  as S_Flame,
  FolderIcon                as S_Folder,
  FolderOpenIcon            as S_FolderOpen,
  FunnelIcon                as S_Filter,
  GlobeAltIcon              as S_Globe,
  HandThumbDownIcon         as S_ThumbsDown,
  HandThumbUpIcon           as S_ThumbsUp,
  HeartIcon                 as S_Heart,
  HomeIcon                  as S_Home,
  InformationCircleIcon     as S_Info,
  LightBulbIcon             as S_Lightbulb,
  LinkIcon                  as S_Link,
  ListBulletIcon            as S_List,
  LockClosedIcon            as S_Lock,
  LockOpenIcon              as S_Unlock,
  MagnifyingGlassIcon       as S_Search,
  MapIcon                   as S_Map,
  MapPinIcon                as S_MapPin,
  MoonIcon                  as S_Moon,
  MusicalNoteIcon           as S_Music,
  PaperAirplaneIcon         as S_Plane,
  PauseIcon                 as S_Pause,
  PauseCircleIcon           as S_PauseCircle,
  PencilIcon                as S_Edit2,
  PencilSquareIcon          as S_Edit,
  PhoneIcon                 as S_Phone,
  PhotoIcon                 as S_Image,
  PlayIcon                  as S_Play,
  PlayCircleIcon            as S_PlayCircle,
  PlusIcon                  as S_Plus,
  PlusCircleIcon            as S_PlusCircle,
  PowerIcon                 as S_Power,
  QuestionMarkCircleIcon    as S_HelpCircle,
  RectangleGroupIcon        as S_Layout,
  RectangleStackIcon        as S_Layers,
  CalculatorIcon            as S_Calculator,
  ServerIcon                as S_Server,
  ServerStackIcon           as S_ServerStack,
  ShareIcon                 as S_Share2,
  ShieldCheckIcon           as S_Shield,
  ShieldExclamationIcon     as S_ShieldAlert,
  ShoppingBagIcon           as S_ShoppingBag,
  ShoppingCartIcon          as S_ShoppingCart,
  SpeakerWaveIcon           as S_Volume2,
  SpeakerXMarkIcon          as S_VolumeX,
  StarIcon                  as S_Star,
  StopIcon                  as S_Stop,
  StopCircleIcon            as S_StopCircle,
  SunIcon                   as S_Sun,
  TagIcon                   as S_Tag,
  TrashIcon                 as S_Trash,
  TrophyIcon                as S_Trophy,
  UserIcon                  as S_User,
  UsersIcon                 as S_Users,
  VideoCameraIcon           as S_Video,
  WifiIcon                  as S_Wifi,
  WrenchIcon                as S_Wrench,
  XCircleIcon               as S_XCircle,
  XMarkIcon                 as S_X,
} from '@heroicons/react/24/solid';

// ── Public type ───────────────────────────────────────────────────────────────
export type HeroiconFC = React.FC<React.SVGProps<SVGSVGElement>>;

interface HeroiconPair { outline: HeroiconFC; solid: HeroiconFC }

// ── Lucide name → Heroicons pair ──────────────────────────────────────────────
// Keys must exactly match the Lucide PascalCase icon names used in this codebase
// (both built-in constants and YAML labels['type-icon'] values).
const REGISTRY: Record<string, HeroiconPair> = {
  // ── Built-in category icons ────────────────────────────────────────────────
  Plane:       { outline: O_Plane,       solid: S_Plane       },
  Calculator:  { outline: O_Calculator,  solid: S_Calculator  },
  Layers:      { outline: O_Layers,      solid: S_Layers      },
  CheckCircle: { outline: O_CheckCircle, solid: S_CheckCircle },
  Monitor:     { outline: O_Monitor,     solid: S_Monitor     },

  // ── Built-in pattern icons ─────────────────────────────────────────────────
  Zap:         { outline: O_Bolt,        solid: S_Bolt        },
  Settings:    { outline: O_Settings,    solid: S_Settings    },
  Database:    { outline: O_Database,    solid: S_Database    },
  Share2:      { outline: O_Share2,      solid: S_Share2      },

  // ── Built-in role icons ────────────────────────────────────────────────────
  Eye:         { outline: O_Eye,         solid: S_Eye         },
  Lightbulb:   { outline: O_Lightbulb,   solid: S_Lightbulb   },

  // ── Default fallback icon ──────────────────────────────────────────────────
  Wrench:      { outline: O_Wrench,      solid: S_Wrench      },

  // ── Common YAML labels['type-icon'] values ─────────────────────────────────
  Activity:          { outline: O_ChartBar,      solid: S_ChartBar      },
  Adjustments:       { outline: O_Adjustments,   solid: S_Adjustments   },
  SlidersHorizontal: { outline: O_Adjustments,   solid: S_Adjustments   },
  Sliders:           { outline: O_Adjustments,   solid: S_Adjustments   },
  AlertCircle:       { outline: O_AlertCircle,   solid: S_AlertCircle   },
  AlertTriangle:     { outline: O_AlertTriangle, solid: S_AlertTriangle },
  Archive:           { outline: O_Archive,       solid: S_Archive       },
  ArchiveBox:        { outline: O_Archive,       solid: S_Archive       },
  Award:             { outline: O_Trophy,        solid: S_Trophy        },
  Trophy:            { outline: O_Trophy,        solid: S_Trophy        },
  BarChart:          { outline: O_ChartBar,      solid: S_ChartBar      },
  BarChart2:         { outline: O_ChartBar,      solid: S_ChartBar      },
  Beaker:            { outline: O_Beaker,        solid: S_Beaker        },
  Flask:             { outline: O_Beaker,        solid: S_Beaker        },
  Bell:              { outline: O_Bell,          solid: S_Bell          },
  Bookmark:          { outline: O_Bookmark,      solid: S_Bookmark      },
  Box:               { outline: O_Box,           solid: S_Box           },
  Package:           { outline: O_Box,           solid: S_Box           },
  Calendar:          { outline: O_Calendar,      solid: S_Calendar      },
  Camera:            { outline: O_Camera,        solid: S_Camera        },
  Chat:              { outline: O_MessageSquare, solid: S_MessageSquare },
  MessageSquare:     { outline: O_MessageSquare, solid: S_MessageSquare },
  MessageCircle:     { outline: O_MessageCircle, solid: S_MessageCircle },
  Clipboard:         { outline: O_Clipboard,     solid: S_Clipboard     },
  ClipboardCheck:    { outline: O_Clipboard,     solid: S_Clipboard     },
  Clock:             { outline: O_Clock,         solid: S_Clock         },
  Cloud:             { outline: O_Cloud,         solid: S_Cloud         },
  Code:              { outline: O_Code,          solid: S_Code          },
  Code2:             { outline: O_Code,          solid: S_Code          },
  Terminal:          { outline: O_Terminal,      solid: S_Terminal      },
  Download:          { outline: O_Download,      solid: S_Download      },
  Edit:              { outline: O_Edit,          solid: S_Edit          },
  Edit2:             { outline: O_Edit2,         solid: S_Edit2         },
  Pencil:            { outline: O_Edit2,         solid: S_Edit2         },
  Filter:            { outline: O_Filter,        solid: S_Filter        },
  Flame:             { outline: O_Flame,         solid: S_Flame         },
  Fire:              { outline: O_Flame,         solid: S_Flame         },
  Folder:            { outline: O_Folder,        solid: S_Folder        },
  FolderOpen:        { outline: O_FolderOpen,    solid: S_FolderOpen    },
  Globe:             { outline: O_Globe,         solid: S_Globe         },
  Globe2:            { outline: O_Globe,         solid: S_Globe         },
  Heart:             { outline: O_Heart,         solid: S_Heart         },
  HelpCircle:        { outline: O_HelpCircle,    solid: S_HelpCircle    },
  Home:              { outline: O_Home,          solid: S_Home          },
  Image:             { outline: O_Image,         solid: S_Image         },
  Photo:             { outline: O_Image,         solid: S_Image         },
  Info:              { outline: O_Info,          solid: S_Info          },
  Layout:            { outline: O_Layout,        solid: S_Layout        },
  Link:              { outline: O_Link,          solid: S_Link          },
  List:              { outline: O_List,          solid: S_List          },
  Lock:              { outline: O_Lock,          solid: S_Lock          },
  Unlock:            { outline: O_Unlock,        solid: S_Unlock        },
  Mail:              { outline: O_Mail,          solid: S_Mail          },
  Envelope:          { outline: O_Mail,          solid: S_Mail          },
  Map:               { outline: O_Map,           solid: S_Map           },
  MapPin:            { outline: O_MapPin,        solid: S_MapPin        },
  Menu:              { outline: O_Menu,          solid: S_Menu          },
  Moon:              { outline: O_Moon,          solid: S_Moon          },
  Music:             { outline: O_Music,         solid: S_Music         },
  Pause:             { outline: O_Pause,         solid: S_Pause         },
  PauseCircle:       { outline: O_PauseCircle,   solid: S_PauseCircle   },
  Phone:             { outline: O_Phone,         solid: S_Phone         },
  Play:              { outline: O_Play,          solid: S_Play          },
  PlayCircle:        { outline: O_PlayCircle,    solid: S_PlayCircle    },
  Plus:              { outline: O_Plus,          solid: S_Plus          },
  PlusCircle:        { outline: O_PlusCircle,    solid: S_PlusCircle    },
  Power:             { outline: O_Power,         solid: S_Power         },
  ToggleLeft:        { outline: O_Power,         solid: S_Power         },
  ToggleRight:       { outline: O_Power,         solid: S_Power         },
  RefreshCw:         { outline: O_Refresh,       solid: S_Refresh       },
  RotateCcw:         { outline: O_Refresh,       solid: S_Refresh       },
  RotateCw:          { outline: O_Refresh,       solid: S_Refresh       },
  Search:            { outline: O_Search,        solid: S_Search        },
  Server:            { outline: O_Server,        solid: S_Server        },
  Shield:            { outline: O_Shield,        solid: S_Shield        },
  ShieldAlert:       { outline: O_ShieldAlert,   solid: S_ShieldAlert   },
  ShoppingBag:       { outline: O_ShoppingBag,   solid: S_ShoppingBag   },
  ShoppingCart:      { outline: O_ShoppingCart,  solid: S_ShoppingCart  },
  Smartphone:        { outline: O_Smartphone,    solid: S_Smartphone    },
  Speaker:           { outline: O_Volume2,       solid: S_Volume2       },
  Volume2:           { outline: O_Volume2,       solid: S_Volume2       },
  VolumeX:           { outline: O_VolumeX,       solid: S_VolumeX       },
  Star:              { outline: O_Star,          solid: S_Star          },
  Stop:              { outline: O_Stop,          solid: S_Stop          },
  StopCircle:        { outline: O_StopCircle,    solid: S_StopCircle    },
  Sun:               { outline: O_Sun,           solid: S_Sun           },
  Tag:               { outline: O_Tag,           solid: S_Tag           },
  ThumbsUp:          { outline: O_ThumbsUp,      solid: S_ThumbsUp      },
  ThumbsDown:        { outline: O_ThumbsDown,    solid: S_ThumbsDown    },
  Trash:             { outline: O_Trash,         solid: S_Trash         },
  Trash2:            { outline: O_Trash,         solid: S_Trash         },
  Upload:            { outline: O_Upload,        solid: S_Upload        },
  User:              { outline: O_User,          solid: S_User          },
  Users:             { outline: O_Users,         solid: S_Users         },
  Video:             { outline: O_Video,         solid: S_Video         },
  Wifi:              { outline: O_Wifi,          solid: S_Wifi          },
  X:                 { outline: O_X,             solid: S_X             },
  XCircle:           { outline: O_XCircle,       solid: S_XCircle       },
};

/**
 * Resolve a Lucide icon name to a Heroicon component (outline or solid).
 * Returns null when no mapping exists for the given name.
 */
export const resolveHeroicon = (lucideName: string, solid: boolean): HeroiconFC | null => {
  const entry = REGISTRY[lucideName];
  if (!entry) return null;
  return solid ? entry.solid : entry.outline;
};

/** Fallback Heroicon when nothing else matches (outline Wrench). */
export const HEROICON_FALLBACK_OUTLINE: HeroiconFC = O_Wrench;
export const HEROICON_FALLBACK_SOLID:   HeroiconFC = S_Wrench;
